name: build docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    name: build and push docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write	
    steps:
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/vgropp/tempsense-exporter:latest	
