name: build docker

on:
  workflow_run:
    workflows: [golangci-lint, Test]
    types:
      - completed

jobs:
  build-and-push:
    name: build and push docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write	
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/vgropp/tempsense-exporter:latest	
