name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...